CREATE TABLE spiders (
    "RECORD" VARCHAR(6) DEFAULT 'RECORD', --UPD
    id TEXT,
    type VARCHAR(15) NOT NULL,
    modified VARCHAR(15),
    "language" VARCHAR(15),
    license VARCHAR(15) NOT NULL,
    rightsholder TEXT,
    "references" TEXT NOT NULL,
    bibliographiccitation TEXT,
    institutionid TEXT,
    institutioncode TEXT,
    ownerinstitutioncode TEXT,
    collectioncode TEXT,
    datasetname TEXT,
    basisofrecord VARCHAR(20) NOT NULL,
    dynamicproperties TEXT,
    "OCCURRENCE" VARCHAR(10) DEFAULT 'OCCURRENCE', --UPD
    occurrencestatus VARCHAR(15) NOT NULL,
    disposition VARCHAR(20),
    occurrenceid TEXT NOT NULL,
    catalognumber TEXT,
    recordedby TEXT,
    individualcount INT,
    organismquantity REAL,
    organismquantitytype TEXT,
    sex VARCHAR(100),
    lifestage VARCHAR(100),
    associatedreferences TEXT,
    associatedtaxa TEXT,
    establishmentmeans VARCHAR(35),
    occurrenceremarks TEXT,
    "EVENT" VARCHAR(5) DEFAULT 'EVENT', --UPD
    eventid VARCHAR(100),
    parenteventid VARCHAR(100),
    fieldnumber VARCHAR(100),
    eventdate VARCHAR(25),
    startdayofyear INT,
    enddayofyear INT,
    "year" INT,
    "month" INT,
    "day" INT,
    verbatimeventdate VARCHAR(100),
    habitat TEXT,
    samplingprotocol TEXT,
    samplingeffort TEXT,
    samplesizevalue REAL,
    samplesizeunit VARCHAR(100),
    eventremarks TEXT,
    "LOCATION" VARCHAR(10) DEFAULT 'LOCATION', --UPD
    locationid VARCHAR(100),
    highergeography VARCHAR(100),
    continent VARCHAR(30),
    country VARCHAR(30),
    countrycode VARCHAR(3),
    stateprovince VARCHAR(100),
    county VARCHAR(100),
    municipality VARCHAR(100),
    locality TEXT,
    verbatimlocality TEXT,
    minimumelevationinmeters INT,
    maximumelevationinmeters INT,
    decimallatitude FLOAT,
    decimallongitude FLOAT,
    geodeticdatum VARCHAR(30),
    coordinateuncertaintyinmeters INT,
    coordinateprecision REAL,
    verbatimCoordinates VARCHAR(50),
    georeferencedby VARCHAR(200),
    georeferenceddate VARCHAR(10),
    locationremarks TEXT,
    "IDENTIFICATION" VARCHAR(15) DEFAULT 'IDENTIFICATION', --UPD
    identifiedby VARCHAR(200),
    dateidentified VARCHAR(10),
    verbatimidentification VARCHAR(100),
    identificationremarks TEXT,
    "TAXON" VARCHAR(5) DEFAULT 'TAXON', --UPD
    taxonrank VARCHAR(10),
    scientificname VARCHAR(100) NOT NULL,
    kingdom VARCHAR(10) DEFAULT 'Animalia',
    phylum VARCHAR(10) DEFAULT 'Arthropoda',
    class VARCHAR(10) DEFAULT 'Arachnida',
    "order" VARCHAR(10),
    family VARCHAR(30),
    genus VARCHAR(30),
    specificepithet VARCHAR(50),
    scientificnameauthorship VARCHAR(100),
    canonicalname VARCHAR(100),
    acceptednameusage VARCHAR(100),
    type_status VARCHAR(30),
    taxonRemarks TEXT,
    "REMOVE" VARCHAR(6) DEFAULT 'REMOVE', --UPD
    publ_id INT NOT NULL,
    vol_ids TEXT,
    shortlink varchar(30) NOT NULL
);
